---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: relaxdiego/sampleapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 4567
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
kind: Service
apiVersion: v1
metadata:
  name: sampleapp
spec:
  selector:
    app: sampleapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4567
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sampleapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sampleapp.homelab
    http:
      paths:
      - path: /
        backend:
          serviceName: sampleapp
          servicePort: 80
