---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-v2
  labels:
    app: sampleapp-v2
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: sampleapp-v2
  template:
    metadata:
      labels:
        app: sampleapp-v2
    spec:
      containers:
      - name: sampleapp
        image: relaxdiego/sampleapp:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---

kind: Service
apiVersion: v1
metadata:
  name: sampleapp-v2
spec:
  selector:
    app: sampleapp-v2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sampleapp-v2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sampleapp-v2.local
    http:
      paths:
      - path: /
        backend:
          serviceName: sampleapp-v2
          servicePort: 80
